### ISSUE TITLE
有坑

### ISSUE THREAD

**Issue by xieruidong521** [earnp/laravel-google-authenticator#2]
/**
     * Get QR-Code URL for image, from google charts
     *
     * @param string $name
     * @param string $secret
     * @param string $title
     * @return string
     */
    public function getQRCodeGoogleUrl($name, $secret, $title = null) {
        $urlencoded = urlencode('otpauth://totp/'.$name.'?secret='.$secret.'');
	if(isset($title)) {
                $urlencoded .= urlencode('&issuer='.urlencode($title));
        }
        return $urlencoded;
    }
如果你用到了这个方法，则生成的qrcode会无法识别，正确的应该是这样：
public function getQRCodeGoogleUrl($name, $secret, $title = null) {
        $urlencoded = 'otpauth://totp/'.$name.'?secret='.$secret.'';
	if(isset($title)) {
                $urlencoded .= '&issuer='.urlencode($title);
        }
        return $urlencoded;
    }
当然了，name有中文的话还是得encode

**Comment by kuwo88** [comment]
用你这种方法也可以,还有可以在config/google.php中设置name为urlencode的中文

**Comment by xieruidong521** [comment]
按大佬的来
